import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
const Home: NextPage = () => {
  const [semel, setSemel] = useState(0)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const link = useMemo(() => {
    return `/api/studygroups?semel=${semel}&username=${username}&password=${password}`
  }, [password, semel, username])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center h-screen justify-center flex-col gap-4">
        <input
          placeholder="סמל בית ספר וזה"
          className="bg-zinc-200 p-2 px-4 rounded-lg placeholder:text-black text-lg text-right"
          onChange={(e) => setSemel(Number(e.target.value))}
        />

        <input
          placeholder="שם משתמש"
          className="bg-zinc-200 p-2 px-4 rounded-lg placeholder:text-black text-lg text-right"
          onChange={(e) => setUsername(e.target.value)}
        />
        <input
          placeholder="סיסמה"
          className="bg-zinc-200 py-2 px-4 rounded-lg placeholder:text-black text-lg text-right"
          onChange={(e) => setPassword(e.target.value)}
        />
        <Link href={link}>
          <a className="bg-sky-500 text-white font-bold py-3 px-6 rounded-xl">
            להתחבר וזה עניינות
          </a>
        </Link>
      </div>
    </div>
  )
}

export default Home
