import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import Dashboard from '../components/Dashboard'
import Login from '../components/Login'
import Logo from '../components/Logo'
import LoginView from '../components/Views/LoginView'
import DashboardView from '../components/Views/DashboardView'
import { IFrontStudyGroup } from '../Interfaces'
const Home: NextPage = () => {
  const [data, setData] = useState<IFrontStudyGroup[]>([])

  return (
    <div className="flex flex-col h-full w-screen m-0 p-0 justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.length ? (
        <DashboardView subjects={data} />
      ) : (
        <LoginView setData={(data) => setData(data)} />
      )}
    </div>
  )
}

export default Home
